### ISSUE TITLE
notifyDataSetChanged()这个方法没用？

### ISSUE THREAD

**Issue by andansky** [Solartisan/TurboRecyclerViewHelper#2]
notifyDataSetChanged()这个方法没用？怎么刷新数据？

**Comment by solartcc** [comment]
在封装的add/addData/remove/resetData等方法中已经封装了notify，请问你遇到什么问题了吗？

**Comment by andansky** [comment]
就比如说我刚开始数据列表是空的，获取数据之后刷新是用哪个方法？
为什么直接调用mListView.loadMoreComplete(listData);不行呢？

**Comment by solartcc** [comment]
一般配合上拉加载使用loadMoreComplete方法刷新数据，且要求Adapter需要继承BaseTurboAdapter；一般状态下可以使用BaseTurboAdapter中封装的addData(List<T> data)等方法添加数据。另外可以阅读readme中的简单用法及demo。以上，希望能帮到你。
